Update to 4.1+ qBittorrent APIs
v1k45/python-qBittorrent pull request #36
Opened 2019-12-08 18:29 UTC by Shaance

2019-12-11 14:55 UTC, v1k45 commented
Thanks for the awesome contribution, @Shaance!
But I am afraid this will break v3 support. I'll take a deeper look this weekend.

2019-12-16 03:15 UTC, v1k45 reviewed
The code changes are looking good.
I guess we can live with this breaking 3.1x. The version is quite old anyway. An older (current) version of this project can be used for supporting 3.1.x.

Could you go ahead and update the README file to reflect the version support?

2019-12-16 03:15 UTC, v1k45 commented on qbittorrent/client.py
> +
Dead code. Needs to be removed.

2019-12-16 07:54 UTC, Shaance commented
@v1k45 Updated the README and removed the dead code :)

2019-12-23 00:42 UTC, v1k45 requested changes
Just tested this, few methods aren't working, otherwise everything works fine.

2019-12-23 00:42 UTC, v1k45 commented on qbittorrent/client.py
> +        return self._post('torrents/delete', data={'hashes': 'all'})
This isn't working.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vikas/code/oss/python-qBittorrent/qbittorrent/client.py", line 513, in delete_all
    return self._post('torrents/delete', data={'hashes': 'all'})
  File "/home/vikas/code/oss/python-qBittorrent/qbittorrent/client.py", line 55, in _post
    return self._request(endpoint, 'post', data, **kwargs)
  File "/home/vikas/code/oss/python-qBittorrent/qbittorrent/client.py", line 79, in _request
    request.raise_for_status()
  File "/home/vikas/.virtualenvs/qbittorrent/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://127.0.0.1:8080/api/v2/torrents/delete
>>> 
```

I looked into it and it is happening because of missing `deleteFiles` parameter.

2019-12-23 00:42 UTC, v1k45 commented on qbittorrent/client.py
> +        options['urls'] = link
This breaks support for passing a `list` of links. Was there a specific reason for doing this?

2019-12-23 00:42 UTC, v1k45 commented on qbittorrent/client.py
> +    def force_start(self, infohash_list, value=False):
I think we should remove the default `value` parameter/arg so that this method is clearer, what do you think?

```python
client.force_start('abc123...321cab', force_start=True)
client.force_start('abc123...321cab', force_start=False)
# vs
client.force_start('abc123...321cab', value=True)
client.force_start('abc123...321cab')
```

2019-12-23 00:42 UTC, v1k45 commented on qbittorrent/client.py
>      def preferences(self):
Preferences isn't working due to the way it is implemented. The fix for this is to replace

```python
super(Proxy, self).__init__(url)
```

with 

```python
self.url = url
```

2019-12-23 02:25 UTC, v1k45 commented on qbittorrent/client.py
> +        return self._post('torrents/delete', data={'hashes': 'all'})
Fixed in 20f80c8.

2019-12-23 02:25 UTC, v1k45 commented on qbittorrent/client.py
>      def preferences(self):
Fixed in 20f80c8.

2019-12-23 02:25 UTC, v1k45 commented on qbittorrent/client.py
> +        options['urls'] = link
Fixed in 20f80c8.

2019-12-23 21:42 UTC, Shaance commented on qbittorrent/client.py
> +    def force_start(self, infohash_list, value=False):
Yes I agree, going to make the change

2019-12-24 17:56 UTC, v1k45 approved these changes
Thanks for the awesome work! I'll bump the package version and deploy it to PyPI soon.

2019-12-24 17:56 UTC, merged

2019-12-24 18:17 UTC, v1k45 commented
This update is live in 0.4.1 🎉 

https://pypi.org/project/python-qbittorrent/0.4.1/